datav:
    image: busybox
    volumes:
        - /virtuoso_db/

virtuoso:
    image: eeacms/virtuoso:latest
    ports:
        - 1111:1111
        - 1112:1112
    volumes_from:
        - datav
    env_file:
        - virtuoso.env
