shared_volumes:
    image: busybox
    volumes:
        - /virtuoso_db/
        - ./virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini:z
        - /shared_folder/local/cr3/files:z
        - /shared_folder/backups/sql:z
        - /shared_folder/tmp:z

virtuoso:
    restart: always
    image: eeacms/virtuoso:7.2.1 
    ports:
        - 8890:8890
        - 1111:1111
    volumes_from:
        - shared_volumes
